name: agapenv
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip



  # Scientific stack
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.16.2
  - scikit-learn=1.8.0
  - joblib=1.5.3
  - xgboost=3.2.0

  # Cheminformatics
  - rdkit=2025.09.5
  - mordred=1.2.0
  - networkx=2.8.8

  # Utilities
  - matplotlib=3.10.8
  - openpyxl=3.1.5
  - requests=2.33.1
  - pillow=12.2.0
  - asgiref==3.11.0
  - sqlparse==0.5.5

  
  - pip:
      - gunicorn==22.0.0
      - whitenoise==6.7.0
      - tensorflow==2.20.0
      - keras==3.14.0
      - django-extensions==4.1
        # Django / web
      - django==5.1.15
